name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker run -p 5000:5000 -d ghcr.io/aarnav-d/k8s-py-mon:v2.0.0
        sleep 2
        curl 127.0.0.1:5000
